### ISSUE TITLE
Paths for replacement seem wrong

### ISSUE THREAD

**Issue by zhangjb35** [jiayiliu-pku/sleep_scoring_mne#1]
Hi,
I install the latest version of anoconda, and get wrong when I try to replace these scripts. Seem these paths are wrong, they should be in the following path:
> /home/jinbo/anaconda3/envs/mne_sleep_scoring/lib/python3.9/site-packages/mne/viz/
> /home/jinbo/anaconda3/envs/mne_sleep_scoring/lib/python3.9/site-packages/mne

**Comment by jiayiliu-pku** [comment]
Thank you very much for your bug report.
Please offer your system, mne and conda version.

**Comment by zhangjb35** [comment]
using these code:
```bash
conda --version
echo ---------
lsb_release -a
echo ---------
pip show mne
```

results:
```bash
conda 4.11.0
---------
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
---------
Name: mne
Version: 0.24.1
Summary: MNE-Python project for MEG and EEG data analysis.
Home-page: https://mne.tools/dev/
Author: 
Author-email: 
License: BSD-3-Clause
Location: /home/jinbo/anaconda3/envs/mne_sleep_scoring/lib/python3.9/site-packages
Requires: numpy, scipy
Required-by: mne-qt-browser
```
